### ISSUE TITLE
Inserting wait/timeout between commands

### ISSUE THREAD

**Issue by jagged3dge** [geddski/macros#16]
Is there currently any way to introduce a (preferably adjustable) timeout in between macro commands?
If not, I think it would make a super-useful addition to this brilliant extension!

My use-case:
I am using the jest extension for vscode that allows for automatic running tests within VSCode's extension pane. However, sometimes (not blaming the plugin author) it doesn't seem to work. The only workaround is to stop and start the runner. To make this simpler, I'm using this `macros` extension to do the restarting automatically. However, sometimes the `restartJest` macro fails because the `jest.stop` hasn't completed execution properly before the next command `jest.start` is called. Inserting a short timeout (of say, 200ms) would be good enough to make the macro work smoothly.

Thoughts?

**Comment by IanNS333** [comment]
+1

**Comment by osdavison** [comment]
There is an open pull request with this functionality in it [here](https://github.com/geddski/macros/pull/13), but the author hasn't merged it in yet. If you want to use this functionality now, you can copy the contents of [this file](https://github.com/AlteredConstants/macros/blob/88704802607bfce62c94f3bee303096d244e917f/extension.js) into your local copy of this extension which should be at C:\Users\{YOUR_NAME}\.vscode\extensions\geddski.macros-1.2.0\extension.js.

Then just use the delay command from the below macro.

```
"macros": {
  "addSemicolon": [
    "cursorEnd",
    {"command": "$delay", "args": {"milliseconds": 1000}},
    {"command": "type", "args": {"text": ";"}}
  ]
}
```

**Comment by jagged3dge** [comment]
@osdavison Thanks for pointing me to the pull request. This definitely solves my issue. :+1: 
Closing this in favor of open pull request #13

**Comment by deckberg-quantumdigital** [comment]
Thank so much.  Totally worked!  Had a macro that would take my selected text and copy it to clipboard then type some text on the next line, paste, then type some more.  With the latest vscode the paste was going after both text segments.  Now with a slight delay it works again!

`"print_r": [
            "editor.action.clipboardCopyAction",
            "editor.action.insertLineAfter",
            {"command": "type", "args": {"text": "print_r("}},
            {"command": "$delay", "args": {"milliseconds": 20}},
            "editor.action.clipboardPasteAction",
            {"command": "$delay", "args": {"milliseconds": 0}},
            {"command": "type", "args": {"text": ");die;"}}
        ],`

**Comment by EduYukio** [comment]
To those who will try this solution, it works! Just notice that after you alter the extension.js you have to reload vscode for the new extenstion to be loaded (Ctrl+Shift+P -> Realod Window)
