### ISSUE TITLE
Run different macros per different file type?

### ISSUE THREAD

**Issue by luni3359** [geddski/macros#42]
I want to run an attribute sorter automatically on save but it breaks my file when running it on a php file, is there any way to make macros run differently per file type?

**Comment by usernamehw** [comment]
You can use different `when` conditions when assigning keybindings. Example:
```javascript
"when": "resourceExtname =~ /(.js)|(.vue)$/" // regex that works in .js or .vue files
"when": "resourceExtname == .ts"// works for .ts files
"when": "editorLangId != typescript"// works for all files except .ts
```
