### ISSUE TITLE
Unknown configuration setting

### ISSUE THREAD

**Issue by johnhamm** [geddski/macros#5]
When I put the following in my settings.json file (user settings, not workspace), I get the following:
```
Unknown configuration setting
```
If I put the command in my workspace settings file, I don't get that error.  However, the macros don't work unless they are placed in the user settings file but then I have that warning in my Problems panel.

**Comment by geddski** [comment]
@johnhamm can you paste in what you're you're trying to put in the settings.json?

**Comment by nmsmith22389** [comment]
There is something wrong with the coding that’s why... I noticed that in the default settings.json your extension just adds a couple blank lines which also triggers formatting errors in that file and it also makes the settings in the user settings version not be recognized.

**Comment by kylebradshaw** [comment]
here's a screenshot for reference: 
<img width="1440" alt="unknown configuration" src="https://cloud.githubusercontent.com/assets/27273/23215888/f42cbb7e-f8e1-11e6-8f8a-f8d06c287225.png">

**Comment by kylebradshaw** [comment]
for what it's worth the macro *does* work however, vscode just seems to complain in the settings json

**Comment by danielo515** [comment]
It works on the workspace file with  no problems.

**Comment by geddski** [comment]
fixed in 1.2.1
