### ISSUE TITLE
How to trigger keyboard 'enter'

### ISSUE THREAD

**Issue by DH-Illidan-StormRage** [geddski/macros#52]
A wonderful artifact, but how can I trigger `enter`  to turn to next line  by using macros?  I cant find the command to turn to next line.

**Comment by imAliAzhar** [comment]
Hi @DH-Illidan-StormRage 
Did you figure it out?

**Comment by lanye74** [comment]
You can insert `\n` to bump the line down and maintain tab space (ex. `\t\t\n` outputs `\t\t\[break]\t\t`) or use `\r` for a complete return, ignoring auto-tab.
