### ISSUE TITLE
Better documentation?

### ISSUE THREAD

**Issue by a0s** [geddski/macros#59]
> Create your own custom macros by adding them to your settings.json (Code|File > Preferences > User Settings)

I am a newcomer to vscode. `File > Preferences > User Settings` doesn't open settings.json, but only GUI settings. How to add macros in GUI? 
<img width="1064" alt="Screenshot 2020-12-03 at 14 09 03" src="https://user-images.githubusercontent.com/418868/101002718-23046800-3571-11eb-9a69-73a48b051e4e.png">

**Comment by alexmcmillan** [comment]
@a0s: see at the very top-right there are a couple of white-outline icons?  The first one is `Open Settings (JSON)` - clicking that will open the `settings.json` file.
