### ISSUE TITLE
Output text as part of macro

### ISSUE THREAD

**Issue by lumpysimon** [geddski/macros#8]
Is it possible to output a string to the editor as part of a macro? I don't want to ask for input from the  user, just output a string that is defined in the macro.

For example, to go to end of line and add a semi-colon, I've got this but it doesn't work:

````
"macros": {
    "eolSemiColon": [
        "cursorEnd",
        ";"
        ]
    }
}
````

**Comment by geddski** [comment]
Yep it supports that no problem. You just specify an object instead of a string, and the text you want it to type:

```
"macros": {
    "eolSemiColon": [
        "cursorEnd",
        {"command": "type", "args": {"text": ";"}}
        ]
    }
}
```

**Comment by lumpysimon** [comment]
Brilliant thank you, that works perfectly

**Comment by geddski** [comment]
@lumpysimon you bet!
